### ISSUE TITLE
Daysleft function broken

### ISSUE THREAD

**Issue by trendelkamp** [ryancbutler/Citrix#15]
Hey, 

while testing the script i noticed that the function to calculate the days left is broken, at least for me here. I attached a screenshot with errors. 
Besides that the script runs well.

Thanks

![unbenannt](https://user-images.githubusercontent.com/12778148/34114719-ce54d256-e413-11e7-968c-20747c1a08f5.PNG)

**Comment by ryancbutler** [comment]
Interesting.  Looks like it couldn't get the date from the Netscaler.  What firmware version are you running?

**Comment by trendelkamp** [comment]
Hi Ryan, 

currently i´m running on NS12.0 53.22.nc

**Comment by ryancbutler** [comment]
Just tested and seems to work for me on the latest firmware.  Curious on your date-format.  If you get a chance can you add this above line 244, re-run and post the output of the date?
`write-host "MYDATE: $currentdatestr"`

**Comment by trendelkamp** [comment]
Of course! 

> Connecting HTTP
> MYDATE: Mon Dec 18 19:10:24 2017

**Comment by ryancbutler** [comment]
I am unfortunately not able to replicate the issue.  What version of PowerShell are you running? `$psversiontable`

**Comment by trendelkamp** [comment]
Tested on two machines. On both i get the same error. 

> Name                           Value
> ----                           -----
> PSVersion                      5.1.16299.98
> PSEdition                      Desktop
> PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
> BuildVersion                   10.0.16299.98
> CLRVersion                     4.0.30319.42000
> WSManStackVersion              3.0
> PSRemotingProtocolVersion      2.3
> SerializationVersion           1.1.0.1

> Name                           Value                                                                                                                        
> ----                           -----                                                                                                                        
> PSVersion                      5.1.14393.1884                                                                                                               
> PSEdition                      Desktop                                                                                                                      
> PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                                                      
> BuildVersion                   10.0.14393.1884                                                                                                              
> CLRVersion                     4.0.30319.42000                                                                                                              
> WSManStackVersion              3.0                                                                                                                          
> PSRemotingProtocolVersion      2.3                                                                                                                          
> SerializationVersion           1.1.0.1

**Comment by trendelkamp** [comment]
Hi Ryan, 

i just found out that the NetScaler Powershell Gallery Item has this function included too. 
So, at least from my side troubleshooting isn´t necessary anymore. 

Thanks!

**Comment by ryancbutler** [comment]
Thanks @trendelkamp .  Funny thing that's pretty much the same function since I provided it for the Netscaler module.  Appreciate following up.
