### ISSUE TITLE
Add Citrix WEM Agent

### ISSUE THREAD

**Issue by JonathanPitre** [ryancbutler/Citrix#19]
Please add Citrix WEM Agent versions to the json file.

https://secureportal.citrix.com/Licensing/Downloads/UnrestrictedDL.aspx?DLID=16122&URL=https://downloads.citrix.com/16122/Workspace-Environment-Management-Agent-2203.2.zip

**Comment by ryancbutler** [comment]
I'm trying to locate the root location where it would show all versions that I can scrape. For example when I go to https://www.citrix.com/downloads/citrix-virtual-apps-and-desktops/components/workspace-environment-management-2203.html then select components I don't see WEM listed.

**Comment by JonathanPitre** [comment]
Yeah I noticed the download number for the WEM Agent seems static, only the zip version number changes.

**Comment by ryancbutler** [comment]
Ok, I think if I look at https://www.citrix.com/downloads/citrix-virtual-apps-and-desktops/edition-software/premium-2203.html I can get to it.  Going to take some time since some of the .htm download locations loop back on itself.

**Comment by ryancbutler** [comment]
Closing this for https://github.com/ryancbutler/Citrix_DL_Scrapper/issues/2
